/* LLL Humanize — i18n strings
 * Add remaining LLL languages by copying the "en" block and translating values.
 */
const STRINGS = {
  ja: {
    appTitle: "LLL Humanize",
    tagline: "ライトテーブルの上のテキスト鑑識",
    tabPlagiarism: "剽窃チェック",
    tabDetector: "AIシグナル",
    tabHumanize: "ヒューマナイズ",

    plagTitle: "2つのテキストを比較",
    plagHint: "元のテキストと調査対象のテキストを貼り付けてください。一致する箇所が両方のパネルでハイライトされます。",
    sourceLabel: "元テキスト",
    suspectLabel: "対象テキスト",
    compareBtn: "比較する",
    similarity: "類似度",
    overlapA: "元テキストの一致率",
    overlapB: "対象テキストの一致率",
    verdictNone: "一致なし",
    verdictLow: "わずかな重複",
    verdictMid: "部分的に一致",
    verdictHigh: "大幅に一致",
    shingleNote: "k = {k} トークン · {mode}",
    modeWord: "単語モード",
    modeChar: "文字モード（日中韓）",

    detTitle: "AI文章のシグナル",
    detHint: "文体的なシグナルのみを表示します。文章の作者を確実に判定できるツールは存在せず、このツールもそれを装いません。",
    analyzeBtn: "分析する",
    sampleHuman: "人間のサンプル",
    sampleAI: "AIのサンプル",
    sigUniformity: "文の長さの均一性",
    sigLowVariety: "語彙の多様性の低さ",
    sigNoContractions: "短縮形の少なさ",
    sigHedgeDensity: "AI定型表現",
    sigRepeatedOpeners: "繰り返される文頭",
    composite: "総合シグナル",
    reliabilityLow: "サンプルが短すぎます。約200語未満ではシグナルの信頼性が低くなります。",
    detDisclaimer: "これはシグナルであり、証拠ではありません。これらのパターンは機械生成の文章に多く見られますが、丁寧に書かれた人間の文章（特に非ネイティブの書き手）でも検出されます。個人への告発の根拠として絶対に使用しないでください。",
    rhythm: "文のリズム",
    rhythmCaption: "各文の語数を順に表示 — 人間の文章は通常、不揃いです",

    humTitle: "人間らしいリズムに書き換える",
    humHint: "文の長さに変化をつけ、機械的な文体を取り除きます。最大5,000文字。",
    strengthLabel: "強度",
    strengthLight: "軽く",
    strengthMedium: "標準",
    strengthStrong: "全面的に",
    humanizeBtn: "書き換える",
    humWorking: "書き換え中…",
    humBefore: "元の文章",
    humAfter: "書き換え後",
    humLoop: "結果を再度シグナル分析",
    humEthics: "ご自身の下書きの推敲にお使いください。生成された文章を自作として提出することは、所属機関や勤務先の規定に違反する場合があります。その責任はご自身にあります。",

    charCount: "{n} 文字",
    emptyInput: "先にテキストを貼り付けてください。",
    errorGeneric: "エラーが発生しました。もう一度お試しください。",
    footer: "LLLシリーズ教材ツール · スコアはあくまで説明用であり、証拠にはなりません",
  },

  en: {
    appTitle: "LLL Humanize",
    tagline: "Text forensics on the light table",
    tabPlagiarism: "Plagiarism",
    tabDetector: "AI Signals",
    tabHumanize: "Humanize",

    plagTitle: "Compare two texts",
    plagHint: "Paste a source and a suspect text. Matching passages light up in both panes.",
    sourceLabel: "Source text",
    suspectLabel: "Suspect text",
    compareBtn: "Compare",
    similarity: "Similarity",
    overlapA: "of source matched",
    overlapB: "of suspect matched",
    verdictNone: "NO MATCH",
    verdictLow: "MINOR OVERLAP",
    verdictMid: "PARTIAL MATCH",
    verdictHigh: "SUBSTANTIAL MATCH",
    shingleNote: "k = {k} token shingles · {mode}",
    modeWord: "word mode",
    modeChar: "character mode (CJK)",

    detTitle: "AI-writing signals",
    detHint: "Stylometric signals only — no tool can reliably prove authorship, and this one does not pretend to.",
    analyzeBtn: "Analyze",
    sampleHuman: "Human sample",
    sampleAI: "AI sample",
    sigUniformity: "Sentence uniformity",
    sigLowVariety: "Low lexical variety",
    sigNoContractions: "Absence of contractions",
    sigHedgeDensity: "Stock AI phrases",
    sigRepeatedOpeners: "Repeated sentence openers",
    composite: "Composite signal",
    reliabilityLow: "Sample too short — signals unreliable below ~200 words.",
    detDisclaimer: "Signals, not proof. These patterns appear in machine text more often, but careful human writing (especially by non-native speakers) triggers them too. Never use this as evidence against a person.",
    rhythm: "Sentence rhythm",
    rhythmCaption: "words per sentence, in order — human writing is usually jagged",

    humTitle: "Rewrite with a human rhythm",
    humHint: "Rewrites text to vary sentence length and drop the machine register. Max 5,000 characters.",
    strengthLabel: "Strength",
    strengthLight: "Light touch",
    strengthMedium: "Medium",
    strengthStrong: "Full rewrite",
    humanizeBtn: "Rewrite",
    humWorking: "Rewriting…",
    humBefore: "Original",
    humAfter: "Rewritten",
    humLoop: "Re-run signals on result",
    humEthics: "For editing your own drafts. Passing off generated work as your own may violate your institution's or employer's policies — that part is on you.",

    charCount: "{n} characters",
    emptyInput: "Paste some text first.",
    errorGeneric: "Something went wrong. Try again.",
    footer: "An LLL Series teaching tool · scores are illustrations, not evidence",
  },

  "zh-CN": {
    appTitle: "LLL Humanize",
    tagline: "文本取证观察台",
    tabPlagiarism: "查重",
    tabDetector: "AI 信号",
    tabHumanize: "润写",

    plagTitle: "对比两段文本",
    plagHint: "粘贴源文本与待查文本，重合段落会在两栏中同时高亮。",
    sourceLabel: "源文本",
    suspectLabel: "待查文本",
    compareBtn: "对比",
    similarity: "相似度",
    overlapA: "源文本被匹配比例",
    overlapB: "待查文本被匹配比例",
    verdictNone: "无匹配",
    verdictLow: "轻微重合",
    verdictMid: "部分匹配",
    verdictHigh: "大量匹配",
    shingleNote: "k = {k} 词块 · {mode}",
    modeWord: "词模式",
    modeChar: "字符模式（中日韩）",

    detTitle: "AI 写作信号",
    detHint: "仅为文体信号——没有任何工具能可靠证明作者身份，本工具也不假装可以。",
    analyzeBtn: "分析",
    sampleHuman: "人类样本",
    sampleAI: "AI 样本",
    sigUniformity: "句长均匀度",
    sigLowVariety: "词汇多样性低",
    sigNoContractions: "缺少缩写形式",
    sigHedgeDensity: "AI 常用套话",
    sigRepeatedOpeners: "重复的句首结构",
    composite: "综合信号",
    reliabilityLow: "样本太短——少于约 200 词时信号不可靠。",
    detDisclaimer: "这是信号，不是证据。这些模式在机器文本中更常见，但严谨的人类写作（尤其是非母语者）同样会触发。切勿以此指控任何人。",
    rhythm: "句子节奏",
    rhythmCaption: "按顺序显示每句词数——人类写作通常参差不齐",

    humTitle: "以人类节奏改写",
    humHint: "改写文本以变化句长、去除机器腔。最多 5,000 字符。",
    strengthLabel: "力度",
    strengthLight: "轻改",
    strengthMedium: "中等",
    strengthStrong: "全面改写",
    humanizeBtn: "改写",
    humWorking: "改写中…",
    humBefore: "原文",
    humAfter: "改写后",
    humLoop: "对结果重新分析信号",
    humEthics: "用于润色你自己的草稿。将生成内容冒充原创可能违反你所在学校或公司的规定——责任自负。",

    charCount: "{n} 字符",
    emptyInput: "请先粘贴文本。",
    errorGeneric: "出错了，请重试。",
    footer: "LLL 系列教学工具 · 分数仅作演示，不能作为证据",
  },
};

function t(lang, key, vars) {
  let s = (STRINGS[lang] && STRINGS[lang][key]) || STRINGS.en[key] || key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace("{" + k + "}", v);
  return s;
}
